config/routes.rb
Rails.application.routes.draw do
  resources :sessions

  resources :users do
    resources :uploads
  end

  resources :uploads

  resources :states do
    resources :cities
  end

  resources :cities do
    resources :counties
  end

  resources :counties

  get 'cities/:state', to: 'application#cities'

  get '/register' => 'users#create'

  get '/upload' => 'uploads#new'

  get '/login' => 'sessions#new'

  post  '/login' => 'sessions#create'

  get '/logout', to: 'sessions#destroy'

  get '/', to: 'welcome#index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :counties
end

app/models/county.rb
class County < ApplicationRecord
	belongs_to :city
end

app/models/state.rb
class State < ApplicationRecord
	has_many :cities
end

app/models/upload.rb
class Upload < ApplicationRecord
  
  belongs_to :user
  has_attached_file :file
  do_not_validate_attachment_file_type :file

end

app/models/user.rb
class User < ApplicationRecord
	has_many :uploads

	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
	include UploadsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	def index
		@cities= @state.cities.all
	end

	def new
	end
	
	def create
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if @user && @user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      redirect_to @user
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/states_controller.rb
class StatesController < ApplicationController
	def new
	end

	def index

		if request.xhr?
	    else

		end
	end
	
	def create
	end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
  	if current_user
  		@upload = Upload.new(user_id: current_user.id)
    	@user = current_user
    else
    	redirect_to root_path
    end
    
  end

  def show
    download params[:id]
  end

  def index
  	@user = current_user
  	@uploads = @user.uploads
  end

  def create
     @upload = Upload.new(user_id: current_user.id)

   if @upload.save

     file_name_generated = save_file(
                params[:upload][:file].tempfile, 
                params[:upload][:file].original_filename,
                current_user.id,
                @upload.id)

     @upload.update(
                file: params[:upload][:file].tempfile,
                file_name: file_name_generated,
                file_content_type: params[:upload][:file].content_type)
                #create a document associated with the item that has just been created
                render :index
     @upload.save

   else
     render json: @upload.errors, status: :unprocessable_entity
   end

  end

  # def upload_params
  # 	params.require(:upload).permit(:name, :description , :document, :original_filename, :temp_file) 
  # end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @user = User.all
  end

  def new
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_uploads_path(current_user.id)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
    ActionController::Parameters.permit_all_parameters = true
  end

  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if @current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
       if user && user.authenticated?(:remember, cookies[:remember_token])
        @current_user = user
      end
    end

  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/uploads_helper.rb
module UploadsHelper
	require 'csv'
	require 'fileutils'
	def csv_parse file_path
	  
	    csv = CSV.read(file_path)

	    csv.each do |row|
	    	State.create!(abbreviation: row[0], name: row[1])
	    end

	end

	def text_parce file_path
		File.open(file_path, "r") do |f|
	  	  f.each_line do |line|
	  		line = line.sub!('|',',')
	  		line = line.sub!('|',',')
	  		line = line.sub!('...',',')
	  		line = line.strip
	  		
	  		array = line.split(',')

	  		state = State.find_by(abbreviation: array[2])
	  		city = City.create!(state_id: state.id, name: array[1])
	  		county = County.create!(city_id: city.id, name: array[3], zip: array[0])
	  		p "#{state.name}" + " \t " + "#{city.name}" + " \t " + "#{county.name}" 
	  	  end
	  	end
  	end

	
	def save_file file_path, file_name, user_id, upload_id

		FileUtils.cp(file_path.path, 'app/assets/uploaded_files')
		ext = File.extname(file_path.path)        # => ".mp4"
        base_name = File.basename(file_path.path)

		new_file_name = DateTime.now.month.to_s + 
						DateTime.now.day.to_s   +
						DateTime.now.year.to_s  +
						user_id.to_s   +
						upload_id.to_s + 
						ext

		new_path = 'app/assets/uploaded_files/' + base_name
		File.rename(new_path, 'app/assets/uploaded_files/' + new_file_name)

	    new_file_name
	end

	def download upload_id
		@upload = current_user.uploads.find(upload_id)
        file_path = 'app/assets/uploaded_files/'+@upload.file_name
		send_file file_path, :disposition => 'attachment'
	end
end

app/helpers/users_helper.rb
module UsersHelper    

end

app/views/cities/index.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">ZipCode</th>
      <th scope="col">county</th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
		<tr>
	    
	      <td><%= city.name %></td>
	      <td><%= city.county %></td>
	      <td><%= city.ZipCode%></td>
    	</tr>
   
	<% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorrowApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css"></script>
  </head>

  <body>
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<div>
	<nav class="navbar navbar-inverse f_color">
		<div class="container-fluid">
			<div class="navbar-header ">

			</div>
				<% if logged_in? %>

				<ul class="nav navbar-nav navbar-left">
				  
				  <li ><%= button_to "Profile", user_uploads_path(current_user.id), method: "get", :class => 'navbar-link', :class => "btn btn-sm"  %></li>
				  
				  <li><%= button_to "Logout", session_path(current_user.id), method: "delete", :class => 'navbar-link', :class => "btn btn-sm" %></li>
				  
				   <p class="navbar-text nav navbar-nav navbar-left">Signed in as <a href="#" class="navbar-link"><strong><%= current_user.email %></strong></a></p>

				</ul>
			    <ul class="nav navbar-nav navbar-right">
				   <li><%= button_to "link to state data upload", states_path, method: "get", :class => 'navbar-link', :class => "btn btn-sm" %></li>
				</ul>
				<% else %>
				<ul class="nav navbar-nav">
				  <li><%= button_to "Sign up", new_user_path, method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>

				  <li><%= button_to "Login", new_session_path, method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>
				</ul>
				<% end %>


			
		</div>
	</nav>
</div>

app/views/states/index.html.erb
<div class="zip_request">
        <input type="text" class="form-control" placeholder="enter zipcode" aria-label="enter zipcode here" aria-describedby="basic-addon2">
  
        <button class="send_zip" type="button">send</button>
</div>
  
<div class="zip_response">
  
</div>

</div class="state_request">
        <input type="send" class="form-control" placeholder="enter state abbreviation" aria-label="state abbreviation" aria-describedby="basic-addon2">
  
        <button class="send_abbr" type="button">send</button>
  
</div>


<div class="state_response">
  
</div>

app/views/states/new.html.erb
<div class="upload">
	
</div>
<div class="api">
	
</div>

app/views/uploads/index.html.erb
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">File Name</th>
      <th scope="col">Type</th>
      <th scope="col">download link</th>
    </tr>
  </thead>
  <tbody>
    <% current_user.uploads.each do |upload| %>
		<tr>
	    
	      <td><%= upload.file_name %></td>
	      <td><%= upload.file_content_type %></td>
	      <td><%= link_to "download", user_upload_path(current_user.id,upload.id), method: "get", :class => 'link'  %></td>
    	</tr>
   
	<% end %>
  </tbody>
</table>

<div class="container text-left sign_up_form_top">
    <%= button_to "upload files ... ", new_user_upload_path(current_user.id), method: "get", :class => 'link'  %>
</div>

app/views/uploads/new.html.erb
<%= form_for @upload, url: user_uploads_path, html: { multipart: true } do |form| %>
  <%= form.file_field :file %>
  <%= form.submit %>
<% end %>

app/views/uploads/show.html.erb
<%= @upload.file_name %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="container text-center sign_up_form_top">
  <h2>Sign Up</h2>

  <div class="col-lg-12 form_div">
    <%= f.text_field :name, class: 'text_field', placeholder: 'Name'  %>
  </div>

  <div class="col-lg-12 form_div">
    <%= f.text_field :email, class: 'info_responsive-input', placeholder: 'Email'  %>
  </div>

  <div class="col-lg-12 form_div">
    <%= f.password_field :password,required: true, class: 'info_responsive-input', placeholder: 'Password' %>
  </div>

  <div class="col-lg-12 form_div">
    <%= f.password_field :password_confirmation,required: true, class: 'info_responsive-input', placeholder: 'Password Confirmation'  %>
  </div>

  <div>
    <%= f.submit "signup", class: 'btn sign_up_form_submit' %>
  </div>

  </div>
<% end %>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/users/show.html.erb
<div class="container text-center sign_up_form_top">
	<ul class="nav navbar-nav">
	  <li ><%= button_to "upload", new_user_upload_path(current_user.id), method: "get", :class => 'link', :class => "btn btn-sm btn-margin-left"  %></li>

	  
	  <li><%= button_to "view uploaded documents", user_uploads_path(current_user.id), method: "get", :class => 'link', :class => "btn btn-sm btn-margin-left" %></li>
	</ul>

</div>